"""
Chat API — v1 streaming endpoint.

Provides a Server-Sent Events (SSE) endpoint for real-time AI chat
that streams tokens as they are generated by the Jisr AI agent.
"""

from __future__ import annotations

import json
from typing import Optional

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field
from sse_starlette.sse import EventSourceResponse

from app.agent.assistant import chat, chat_stream

router = APIRouter(prefix="/chat", tags=["Chat"])


# ──────────────────────────────────────────────
# Request / Response schemas
# ──────────────────────────────────────────────
class ChatRequest(BaseModel):
    """Incoming chat message from the frontend."""

    message: str = Field(
        ...,
        min_length=1,
        max_length=4000,
        description="The user's message to the AI assistant.",
        examples=["ما هو إجمالي الرواتب لهذا الشهر؟"],
    )
    session_id: Optional[str] = Field(
        default="default",
        description="Unique session ID for conversation continuity.",
        examples=["sess_abc123"],
    )


class ChatResponse(BaseModel):
    """Non-streaming response."""

    reply: str
    session_id: str


# ──────────────────────────────────────────────
# POST /api/v1/chat  — non-streaming
# ──────────────────────────────────────────────
@router.post(
    "/",
    response_model=ChatResponse,
    summary="Send a message (non-streaming)",
    description="Send a message and receive the complete AI response.",
)
async def chat_endpoint(req: ChatRequest):
    try:
        reply = await chat(req.message, session_id=req.session_id)
        return ChatResponse(reply=reply, session_id=req.session_id)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# ──────────────────────────────────────────────
# POST /api/v1/chat/stream  — SSE streaming
# ──────────────────────────────────────────────
@router.post(
    "/stream",
    summary="Send a message (streaming via SSE)",
    description="Send a message and receive a real-time token stream.",
)
async def chat_stream_endpoint(req: ChatRequest):
    async def event_generator():
        try:
            async for token in chat_stream(req.message, session_id=req.session_id):
                yield {"event": "token", "data": json.dumps({"content": token}, ensure_ascii=False)}
            yield {"event": "done", "data": json.dumps({"status": "complete"})}
        except Exception as e:
            yield {"event": "error", "data": json.dumps({"error": str(e)})}

    return EventSourceResponse(event_generator())
